import CartContextProvider from "@/components/CartContext/CartContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ThemeContextProvider from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <ThemeContextProvider>
          <Navbar />
          <div>{children}</div>
          <Footer />
          </ThemeContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
